version: '3'
services:
  haskell-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: tail -f /dev/null  # keep the container running
    entrypoint: [ "/workspace/.devcontainer/entrypoint.sh" ]
